from .kl import KLSimilarityLoss
from .similarity import SimilarityDistillationLoss
from .composition import CompositionLoss
from .variance import InBatchNegativesVariancePenaltyLoss, LabeledNegativesVariancePenaltyLoss
