run_name: multilingual-e5-base-e-faq-csd
base_model:
  name: intfloat/multilingual-e5-base
output_dir: models/
objectives:
  - type: contrastive
    matryoshka:
      matryoshka_dims: [64, 128, 256, 384, 512, 768]
  - type: similarity
    matryoshka:
      matryoshka_dims: [64, 128, 256, 384, 512, 768]
  - type: distillation
    teacher:
      name: intfloat/multilingual-e5-large-instruct
      args:
        default_prompt_name: quora
        prompts:
          quora: "Instruct: Given a question, retrieve questions that are semantically equivalent to the given question\nQuery: "
args:
  max_steps: 5000
  batch_sampler: "no_duplicates"
  prompts: "query: "
  per_device_train_batch_size: 256
  per_device_eval_batch_size: 64
  gradient_checkpointing: true
  warmup_ratio: 0.1
  learning_rate: 0.00002
  eval_strategy: "steps"
  eval_steps: 200
  save_strategy: "steps"
  save_steps: 200
  save_total_limit: 1
  save_only_model: true
  metric_for_best_model: "cosine_map@1"
  load_best_model_at_end: true
  logging_first_step: true
  logging_strategy: "steps"
  logging_steps: 100
  push_to_hub: false
evaluator_args:
  mrr_at_k: [10]
  ndcg_at_k: [10]
  accuracy_at_k: [1, 10]
  precision_recall_at_k: [1, 10]
  map_at_k: [1, 10]
